version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ${REDIS_SERVICE_NAME}
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - tv-network
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${BACKEND_SERVICE_NAME}
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=redis://${REDIS_SERVICE_NAME}:6379
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - DEBUG=${DEBUG}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-300}
      - CACHE_TTL=${CACHE_TTL:-60}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - tv-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.frontend.unified
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
        - ENVIRONMENT=${ENVIRONMENT}
        - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
        - API_PORT=${API_PORT}
        - BACKEND_URL=${BACKEND_URL:-}
        - APP_VERSION=${APP_VERSION:-1.0.0}
    container_name: ${FRONTEND_SERVICE_NAME}
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
      - API_PORT=${API_PORT}
      - BACKEND_URL=${BACKEND_URL:-}
      - APP_VERSION=${APP_VERSION:-1.0.0}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - tv-network

networks:
  tv-network:
    driver: bridge
    name: tradingview-${ENVIRONMENT}-network